export const redirects = JSON.parse("{}")

export const routes = Object.fromEntries([
  ["/", { loader: () => import(/* webpackChunkName: "index.html" */"E:/桌面/编程实例/易语言实例/Hakutaku/Doc/HakutakuDoc/src/.vuepress/.temp/pages/index.html.js"), meta: {"t":"项目主页","i":"home"} }],
  ["/Air/", { loader: () => import(/* webpackChunkName: "Air_index.html" */"E:/桌面/编程实例/易语言实例/Hakutaku/Doc/HakutakuDoc/src/.vuepress/.temp/pages/Air/index.html.js"), meta: {"t":"Hakutaku_Air","i":"lightbulb"} }],
  ["/Pro/", { loader: () => import(/* webpackChunkName: "Pro_index.html" */"E:/桌面/编程实例/易语言实例/Hakutaku/Doc/HakutakuDoc/src/.vuepress/.temp/pages/Pro/index.html.js"), meta: {"t":"Elaina'sBot","i":"lightbulb"} }],
  ["/Res/", { loader: () => import(/* webpackChunkName: "Res_index.html" */"E:/桌面/编程实例/易语言实例/Hakutaku/Doc/HakutakuDoc/src/.vuepress/.temp/pages/Res/index.html.js"), meta: {"t":"辅助资源","i":"lightbulb"} }],
  ["/Air/JC/FAQ.html", { loader: () => import(/* webpackChunkName: "Air_JC_FAQ.html" */"E:/桌面/编程实例/易语言实例/Hakutaku/Doc/HakutakuDoc/src/.vuepress/.temp/pages/Air/JC/FAQ.html.js"), meta: {"t":"FAQ","i":"lightbulb"} }],
  ["/Air/JC/GetCadr.html", { loader: () => import(/* webpackChunkName: "Air_JC_GetCadr.html" */"E:/桌面/编程实例/易语言实例/Hakutaku/Doc/HakutakuDoc/src/.vuepress/.temp/pages/Air/JC/GetCadr.html.js"), meta: {"t":"获取充值卡教程","i":"lightbulb"} }],
  ["/Air/JC/GetKJ.html", { loader: () => import(/* webpackChunkName: "Air_JC_GetKJ.html" */"E:/桌面/编程实例/易语言实例/Hakutaku/Doc/HakutakuDoc/src/.vuepress/.temp/pages/Air/JC/GetKJ.html.js"), meta: {"t":"获取框架教程","i":"lightbulb"} }],
  ["/Air/JC/LoginAndregeist.html", { loader: () => import(/* webpackChunkName: "Air_JC_LoginAndregeist.html" */"E:/桌面/编程实例/易语言实例/Hakutaku/Doc/HakutakuDoc/src/.vuepress/.temp/pages/Air/JC/LoginAndregeist.html.js"), meta: {"t":"注册登录教程","i":"lightbulb"} }],
  ["/Air/JC/UserCenter.html", { loader: () => import(/* webpackChunkName: "Air_JC_UserCenter.html" */"E:/桌面/编程实例/易语言实例/Hakutaku/Doc/HakutakuDoc/src/.vuepress/.temp/pages/Air/JC/UserCenter.html.js"), meta: {"t":"用户端使用教程","i":"lightbulb"} }],
  ["/Pro/JC/FAQ.html", { loader: () => import(/* webpackChunkName: "Pro_JC_FAQ.html" */"E:/桌面/编程实例/易语言实例/Hakutaku/Doc/HakutakuDoc/src/.vuepress/.temp/pages/Pro/JC/FAQ.html.js"), meta: {"t":"常见问题","i":"lightbulb"} }],
  ["/Pro/JC/ffmpeg.html", { loader: () => import(/* webpackChunkName: "Pro_JC_ffmpeg.html" */"E:/桌面/编程实例/易语言实例/Hakutaku/Doc/HakutakuDoc/src/.vuepress/.temp/pages/Pro/JC/ffmpeg.html.js"), meta: {"t":"语音转码库部署","i":"lightbulb"} }],
  ["/Pro/JC/Getleast.html", { loader: () => import(/* webpackChunkName: "Pro_JC_Getleast.html" */"E:/桌面/编程实例/易语言实例/Hakutaku/Doc/HakutakuDoc/src/.vuepress/.temp/pages/Pro/JC/Getleast.html.js"), meta: {"t":"获取最新版框架","i":"lightbulb"} }],
  ["/Pro/JC/Getlicence.html", { loader: () => import(/* webpackChunkName: "Pro_JC_Getlicence.html" */"E:/桌面/编程实例/易语言实例/Hakutaku/Doc/HakutakuDoc/src/.vuepress/.temp/pages/Pro/JC/Getlicence.html.js"), meta: {"t":"获取订阅许可证","i":"lightbulb"} }],
  ["/Pro/JC/LocalSign.html", { loader: () => import(/* webpackChunkName: "Pro_JC_LocalSign.html" */"E:/桌面/编程实例/易语言实例/Hakutaku/Doc/HakutakuDoc/src/.vuepress/.temp/pages/Pro/JC/LocalSign.html.js"), meta: {"t":"本地签名使用教程","i":"lightbulb"} }],
  ["/Pro/JC/NewApi.html", { loader: () => import(/* webpackChunkName: "Pro_JC_NewApi.html" */"E:/桌面/编程实例/易语言实例/Hakutaku/Doc/HakutakuDoc/src/.vuepress/.temp/pages/Pro/JC/NewApi.html.js"), meta: {"t":"新增Api接口文档","i":"lightbulb"} }],
  ["/Pro/JC/PlugnApiLicence.html", { loader: () => import(/* webpackChunkName: "Pro_JC_PlugnApiLicence.html" */"E:/桌面/编程实例/易语言实例/Hakutaku/Doc/HakutakuDoc/src/.vuepress/.temp/pages/Pro/JC/PlugnApiLicence.html.js"), meta: {"t":"插件Api许可证申请","i":"lightbulb"} }],
  ["/Pro/JC/Update.html", { loader: () => import(/* webpackChunkName: "Pro_JC_Update.html" */"E:/桌面/编程实例/易语言实例/Hakutaku/Doc/HakutakuDoc/src/.vuepress/.temp/pages/Pro/JC/Update.html.js"), meta: {"t":"框架更新","i":"lightbulb"} }],
  ["/Pro/JC/xmsm.html", { loader: () => import(/* webpackChunkName: "Pro_JC_xmsm.html" */"E:/桌面/编程实例/易语言实例/Hakutaku/Doc/HakutakuDoc/src/.vuepress/.temp/pages/Pro/JC/xmsm.html.js"), meta: {"t":"项目声明","i":"lightbulb"} }],
  ["/Pro/JC/xyqh.html", { loader: () => import(/* webpackChunkName: "Pro_JC_xyqh.html" */"E:/桌面/编程实例/易语言实例/Hakutaku/Doc/HakutakuDoc/src/.vuepress/.temp/pages/Pro/JC/xyqh.html.js"), meta: {"t":"协议切换","i":"lightbulb"} }],
  ["/Res/zy/gyqm.html", { loader: () => import(/* webpackChunkName: "Res_zy_gyqm.html" */"E:/桌面/编程实例/易语言实例/Hakutaku/Doc/HakutakuDoc/src/.vuepress/.temp/pages/Res/zy/gyqm.html.js"), meta: {"t":"公益版签名","i":"lightbulb"} }],
  ["/404.html", { loader: () => import(/* webpackChunkName: "404.html" */"E:/桌面/编程实例/易语言实例/Hakutaku/Doc/HakutakuDoc/src/.vuepress/.temp/pages/404.html.js"), meta: {"t":""} }],
  ["/Air/JC/", { loader: () => import(/* webpackChunkName: "Air_JC_index.html" */"E:/桌面/编程实例/易语言实例/Hakutaku/Doc/HakutakuDoc/src/.vuepress/.temp/pages/Air/JC/index.html.js"), meta: {"t":"JC"} }],
  ["/Pro/JC/", { loader: () => import(/* webpackChunkName: "Pro_JC_index.html" */"E:/桌面/编程实例/易语言实例/Hakutaku/Doc/HakutakuDoc/src/.vuepress/.temp/pages/Pro/JC/index.html.js"), meta: {"t":"JC"} }],
  ["/Res/zy/", { loader: () => import(/* webpackChunkName: "Res_zy_index.html" */"E:/桌面/编程实例/易语言实例/Hakutaku/Doc/HakutakuDoc/src/.vuepress/.temp/pages/Res/zy/index.html.js"), meta: {"t":"Zy"} }],
]);
